const assert=require('node:assert/strict');const Candidate=require('../01_app/assets/steps/step03/candidate-selection-controller.js');
(async()=>{
  const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
  function el(){const listeners={};return {dataset:{},disabled:false,textContent:'',listeners,addEventListener:(n,f)=>listeners[n]=f,removeEventListener:n=>delete listeners[n],emit:(n,e)=>listeners[n]?.(e),querySelector(){return null},querySelectorAll(){return []},closest(){return null},scrollIntoView(){this.scrolled=true}}}
  function harness(options={}){let project=options.project===undefined?'p1':options.project;const images=new Map(),imageCandidates=new Map(),videos=new Map(),videoCandidates=new Map(),grid=el(),message=el(),cards=[],rendered=new Map(),calls=[],errors=[];function card(id){const c=el(),imagePrev=el(),imageNext=el(),videoPrev=el(),videoNext=el();c.dataset.scene=id;for(const [b,d] of [[imagePrev,-1],[imageNext,1],[videoPrev,-1],[videoNext,1]]){b.dataset.direction=String(d);b.closest=s=>s==='.storyboard-card'?c:null}c.querySelectorAll=s=>s==='.storyboard-candidate-nav'?[imagePrev,imageNext]:s==='.storyboard-video-candidate-nav'?[videoPrev,videoNext]:[];c.buttons={imagePrev,imageNext,videoPrev,videoNext};cards.push(c);const after=el();rendered.set(id,after);return c}const root={querySelector:s=>s==='#storyboardGrid'?grid:s==='#storyboardMessage'?message:s.startsWith('.storyboard-card')?rendered.get([...rendered.keys()].find(id=>s.includes(id))):null};let request=options.request|| (async(...args)=>calls.push(args));const deps={getRoot:()=>root,request:(...a)=>request(...a),getActiveProjectId:()=>project,getImages:()=>images,getImageCandidates:()=>imageCandidates,getVideos:()=>videos,getVideoCandidates:()=>videoCandidates,renderStoryboardGrid:()=>calls.push(['render']),escapeSelector:v=>v,onError:(f,e)=>errors.push([f,e.message])};return {controller:Candidate.create(deps),root,grid,message,cards,rendered,card,calls,errors,images,imageCandidates,videos,videoCandidates,setProject:v=>project=v,setRequest:v=>request=v}}
  const valid={getRoot(){},request(){},getActiveProjectId(){},getImages(){},getImageCandidates(){},getVideos(){},getVideoCandidates(){},renderStoryboardGrid(){},escapeSelector(){},onError(){}};assert.throws(()=>Candidate.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>Candidate.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);h.controller.mount(h.root);h.controller.mount(h.root);assert.equal(Object.keys(h.grid.listeners).length,1);h.controller.unmount();assert.equal(Object.keys(h.grid.listeners).length,0);h.controller.mount(h.root);let c=h.card('s');h.setProject(null);await assert.rejects(()=>h.controller.selectImage(c.buttons.imageNext),/프로젝트/);h.setProject('p1');await assert.rejects(()=>h.controller.selectImage(null),/버튼/);await assert.rejects(()=>h.controller.selectImage({dataset:{direction:'1'},closest:()=>null}),/장면/);const invalid=el();invalid.dataset.direction='0';invalid.closest=()=>c;await assert.rejects(()=>h.controller.selectImage(invalid),/방향/);c.dataset.scene='';await assert.rejects(()=>h.controller.selectImage(c.buttons.imageNext),/장면 ID/);
  h=harness();c=h.card('s');assert.equal(await h.controller.selectImage(c.buttons.imageNext),undefined);h.imageCandidates.set('s',[{artifact_id:'one'}]);assert.equal(await h.controller.selectImage(c.buttons.imageNext),undefined);assert.equal(h.calls.length,0);h.imageCandidates.set('s',[{uri:'/no-id'},{artifact_id:'ok'}]);h.images.set('s',{artifact_id:'ok'});await assert.rejects(()=>h.controller.selectImage(c.buttons.imageNext),/artifact_id/);
  h=harness();c=h.card('s');const a={artifact_id:'a',uri:'/a',selected:true},b={artifact_id:'b',uri:'/b',selected:false};h.imageCandidates.set('s',[a,b]);h.images.set('s',{...a});h.videos.set('s',{artifact_id:'old'});h.videos.set('other',{artifact_id:'keep'});h.videoCandidates.set('s',[{artifact_id:'historic'}]);await h.controller.selectImage(c.buttons.imagePrev);assert.deepEqual(JSON.parse(h.calls[0][1].body),{project_id:'p1',scene_id:'s',artifact_id:'b'});assert.equal(a.selected,false);assert.equal(b.selected,true);assert.equal(h.images.get('s').artifact_id,'b');assert.equal(h.videos.has('s'),false);assert.equal(h.videos.has('other'),true);assert.equal(h.videoCandidates.get('s').length,1);assert.equal(h.rendered.get('s').scrolled,true);assert.equal(c.buttons.imageNext.disabled,false);
  h=harness();c=h.card('s');const v1={artifact_id:'v1',uri:'/1',selected:false},v2={artifact_id:'v2',uri:'/2',selected:true};h.videoCandidates.set('s',[v1,v2]);h.videos.set('s',{...v2});await h.controller.selectVideo(c.buttons.videoNext);assert.deepEqual(JSON.parse(h.calls[0][1].body),{project_id:'p1',scene_id:'s',artifact_id:'v1'});assert.equal(h.videos.get('s').artifact_id,'v1');assert.equal(h.message.textContent,'선택한 영상 버전이 콘텐츠에 저장되었습니다.');
  h=harness({request:async()=>{throw new Error('select failed')}});c=h.card('s');h.imageCandidates.set('s',[{artifact_id:'a',selected:true},{artifact_id:'b',selected:false}]);h.images.set('s',{artifact_id:'a'});await assert.rejects(()=>h.controller.selectImage(c.buttons.imageNext),/select failed/);assert.equal(h.images.get('s').artifact_id,'a');assert.equal(h.imageCandidates.get('s')[0].selected,true);assert.equal(c.buttons.imageNext.disabled,false);
  const late=deferred();h=harness({request:async()=>late.promise});c=h.card('s');h.imageCandidates.set('s',[{artifact_id:'a'},{artifact_id:'b'}]);h.images.set('s',{artifact_id:'a'});const stale=h.controller.selectImage(c.buttons.imageNext);h.setProject('p2');late.resolve();assert.equal(await stale,undefined);assert.equal(h.images.get('s').artifact_id,'a');assert.equal(h.calls.length,0);assert.equal(h.rendered.get('s').scrolled,undefined);assert.equal(h.message.textContent,'');
  const failure=deferred();h=harness({request:async()=>failure.promise});c=h.card('s');h.imageCandidates.set('s',[{artifact_id:'a'},{artifact_id:'b'}]);h.images.set('s',{artifact_id:'a'});const staleFailure=h.controller.selectImage(c.buttons.imageNext);h.setProject('p2');failure.reject(new Error('late'));await assert.rejects(()=>staleFailure,/late/);assert.equal(h.message.textContent,'');assert.equal(h.calls.length,0);
  const gates=[];h=harness({request:async()=>{const gate=deferred();gates.push(gate);return gate.promise}});const c1=h.card('s1'),c2=h.card('s2');for(const id of ['s1','s2']){h.imageCandidates.set(id,[{artifact_id:`${id}a`},{artifact_id:`${id}b`}]);h.videoCandidates.set(id,[{artifact_id:`${id}v1`},{artifact_id:`${id}v2`}]);h.images.set(id,{artifact_id:`${id}a`});h.videos.set(id,{artifact_id:`${id}v1`})}const same1=h.controller.selectImage(c1.buttons.imageNext),same2=h.controller.selectImage(c1.buttons.imageNext),otherKind=h.controller.selectVideo(c1.buttons.videoNext),otherScene=h.controller.selectImage(c2.buttons.imageNext);assert.equal(gates.length,3);gates.forEach(g=>g.resolve());await Promise.all([same1,same2,otherKind,otherScene]);
  h=harness();c=h.card('s');h.imageCandidates.set('s',[{artifact_id:'a'},{artifact_id:'b'}]);h.images.set('s',{artifact_id:'a'});h.controller.mount(h.root);let prevented=0,stopped=0;await h.grid.emit('click',{target:{closest:s=>s==='.storyboard-candidate-nav'?c.buttons.imageNext:null},preventDefault:()=>prevented++,stopPropagation:()=>stopped++});assert.equal(prevented,1);assert.equal(stopped,1);h.setRequest(async()=>{throw new Error('click fail')});await h.grid.emit('click',{target:{closest:s=>s==='.storyboard-candidate-nav'?c.buttons.imageNext:null},preventDefault(){},stopPropagation(){}});assert.equal(h.message.textContent,'click fail');assert.deepEqual(h.errors,[['image','click fail']]);
  console.log('Candidate selection controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
