const assert = require('node:assert/strict');
const ScriptGeneration = require('../01_app/assets/steps/step02/script-generation-controller.js');

(async()=>{
  function node(){const classes=new Set();return {hidden:true,textContent:'',innerHTML:'',style:{},className:'',classList:{add:name=>classes.add(name),remove:name=>classes.delete(name),contains:name=>classes.has(name)},querySelector(){return null},querySelectorAll(){return []}}}
  function role(){const item=node(),state=node(),result=node();item.querySelector=selector=>selector==='.ai-role-state'?state:selector==='.ai-role-result'?result:null;item.state=state;item.result=result;return item}
  function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}}
  function harness(overrides={}){
    const ids=['aiWorkflowModal','aiProgressBar','aiFootStatus','aiWorkflowSummary','aiNow'];const nodes=Object.fromEntries(ids.map(id=>[id,node()]));const roles=[role(),role(),role()];nodes.aiWorkflowModal.querySelectorAll=selector=>selector==='.ai-role'?roles:[];
    const bodyClasses=new Set();const root={body:{classList:{add:name=>bodyClasses.add(name),remove:name=>bodyClasses.delete(name)}},querySelector:selector=>nodes[selector.slice(1)]||null};
    let now=overrides.now||0;const calls=[];const timers=new Map();let timerId=0;const generated=overrides.generated||{state:{script:{headline:'완성'}},timeline:{scenes:[{id:'s1'}]},document:{id:'doc'}};
    const deps={getRoot:()=>root,configureWorkflowModal:(type,config)=>{calls.push(['configure',type,config]);return overrides.badModal?{}:nodes.aiWorkflowModal},request:async(path,options)=>{calls.push(['request',path,options]);if(overrides.request)return overrides.request(path,options);if(overrides.failPath===path)throw new Error(overrides.error||'generation failed');return path.endsWith('/generate')?generated:{}},getActiveProjectId:()=>overrides.projectId===undefined?'project-1':overrides.projectId,getSelectedKeywordLabels:()=>['돌봄','가족'],now:()=>now,setInterval:(callback,delay)=>{const id=++timerId;timers.set(id,callback);calls.push(['setInterval',delay]);return id},clearInterval:id=>{timers.delete(id);calls.push(['clearInterval',id])},sleep:async ms=>calls.push(['sleep',ms]),setGeneratedState:value=>calls.push(['state',value]),setGeneratedTimeline:value=>calls.push(['timeline',value]),setGeneratedDocument:value=>calls.push(['document',value]),setKeywordLocked:value=>calls.push(['locked',value]),setVoiceProfile:value=>calls.push(['voice',value]),applyTimeline:value=>calls.push(['applyTimeline',value]),removeStoredScript:()=>calls.push(['removeStoredScript']),fillScript:value=>calls.push(['fillScript',value]),applyScript:value=>calls.push(['applyScript',value]),refreshProjectIndex:async()=>calls.push(['refreshProjectIndex']),showStep:value=>calls.push(['showStep',value])};
    return {controller:ScriptGeneration.create(deps),nodes,roles,root,bodyClasses,calls,timers,setNow:value=>{now=value},generated};
  }
  const valid={getRoot(){},configureWorkflowModal(){},request(){},getActiveProjectId(){},getSelectedKeywordLabels(){},now(){},setInterval(){},clearInterval(){},sleep(){},setGeneratedState(){},setGeneratedTimeline(){},setGeneratedDocument(){},setKeywordLocked(){},setVoiceProfile(){},applyTimeline(){},removeStoredScript(){},fillScript(){},applyScript(){},refreshProjectIndex(){},showStep(){}};
  assert.throws(()=>ScriptGeneration.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>ScriptGeneration.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.unmount(),true);assert.equal(h.controller.unmount(),true);
  const broken=harness();delete broken.nodes.aiNow;assert.throws(()=>broken.controller.mount(broken.root),/missing #aiNow/);
  h=harness({badModal:true});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/configured workflow modal/);assert.equal(h.controller.isRunning(),false);

  const plan=deferred();h=harness({request:path=>path.endsWith('/plan')?plan.promise:h.generated});h.controller.mount(h.root);const pending=h.controller.run();assert.equal(h.controller.isRunning(),true);assert.equal(h.nodes.aiWorkflowModal.hidden,false);assert.equal(h.bodyClasses.has('modal-open'),true);assert.equal(h.nodes.aiProgressBar.classList.contains('indeterminate'),true);assert.equal(h.nodes.aiProgressBar.style.width,'');assert.equal(h.roles[0].className,'ai-role active');assert.equal(h.roles[0].state.textContent,'응답 대기 00:00');assert.equal(h.nodes.aiNow.textContent,'대본 작성 중 · 00:00');assert.match(h.nodes.aiWorkflowSummary.textContent,/돌봄, 가족/);
  h.setNow(65000);[...h.timers.values()][0]();assert.equal(h.nodes.aiNow.textContent,'대본 작성 중 · 01:05');assert.match(h.nodes.aiFootStatus.textContent,/GPT 응답 대기 01:05/);assert.strictEqual(h.controller.run(),pending,'duplicate run returns the active promise');assert.equal(h.calls.filter(call=>call[0]==='request').length,1);plan.resolve({});assert.equal(await pending,undefined,'successful workflow preserves its undefined result');

  assert.deepEqual(h.calls.filter(call=>call[0]==='request').map(call=>[call[1],JSON.parse(call[2].body)]),[['/api/script/plan',{project_id:'project-1'}],['/api/script/generate',{project_id:'project-1'}]]);
  const ordered=h.calls.filter(call=>['state','timeline','document','locked','voice','applyTimeline','removeStoredScript','fillScript','applyScript','refreshProjectIndex','showStep'].includes(call[0])).map(call=>call[0]);assert.deepEqual(ordered,['state','timeline','document','locked','voice','applyTimeline','removeStoredScript','fillScript','applyScript','refreshProjectIndex','showStep']);
  assert.equal(h.nodes.aiProgressBar.style.width,'100%');assert.equal(h.nodes.aiWorkflowModal.classList.contains('complete'),true);assert.equal(h.nodes.aiNow.textContent,'대본이 완료되었습니다.');assert.equal(h.nodes.aiWorkflowSummary.textContent,'스키마 검증과 프로젝트 저장이 완료되어 대본과 콘티 초안이 준비됐습니다.');assert.equal(h.nodes.aiWorkflowModal.hidden,true);assert.equal(h.bodyClasses.has('modal-open'),false);assert.equal(h.calls.some(call=>call[0]==='sleep'&&call[1]===1000),true);assert.equal(h.timers.size,0);

  h=harness({failPath:'/api/script/plan',error:'plan failed'});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/plan failed/);assert.equal(h.nodes.aiProgressBar.style.width,'0%');assert.equal(h.nodes.aiProgressBar.classList.contains('indeterminate'),false);assert.equal(h.nodes.aiNow.textContent,'처리를 완료하지 못했습니다.');assert.equal(h.nodes.aiWorkflowSummary.textContent,'스토리보드 생성 중 문제가 발생했습니다.');assert.equal(h.nodes.aiFootStatus.textContent,'plan failed');assert.equal(h.calls.some(call=>call[0]==='sleep'&&call[1]===1500),true);assert.equal(h.timers.size,0);assert.equal(h.nodes.aiWorkflowModal.hidden,true);
  h=harness({failPath:'/api/script/generate',error:'generate failed'});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/generate failed/);assert.equal(h.roles[0].state.textContent,'저장 완료');assert.equal(h.nodes.aiProgressBar.style.width,'0%');assert.equal(h.timers.size,0);
  h=harness({projectId:null});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/대본을 생성할 콘텐츠를 먼저 선택/);assert.equal(h.calls.length,0);assert.equal(h.nodes.aiWorkflowModal.hidden,true);
  const running=deferred();h=harness({request:path=>path.endsWith('/plan')?running.promise:{}});h.controller.mount(h.root);const run=h.controller.run();assert.equal(h.controller.unmount(),false);running.reject(new Error('stop'));await assert.rejects(()=>run,/stop/);assert.equal(h.controller.unmount(),true);
  console.log('Script generation controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
