const assert=require('node:assert/strict');
const View=require('../01_app/assets/steps/step01/step01-project-index-view.js');

(()=>{
  function harness(){const counts=Object.fromEntries(['all','progress','completed','scheduled'].map(key=>[key,{textContent:''}])),rows=[];let empty='';const holder={offsetParent:{},querySelectorAll(selector){if(selector==='[data-project-id],.content-index-empty')return [...rows,{remove(){empty=''}}];if(selector==='.content-index-row[data-project-id]')return rows;return []},insertAdjacentHTML(position,html){if(html.includes('content-index-empty')){empty=html;return}const id=html.match(/data-project-id="([^"]+)"/)?.[1].replaceAll('&lt;','<').replaceAll('&amp;','&'),meta={html:'',insertAdjacentHTML(where,value){this.html+=value}};rows.push({dataset:{projectId:id},html,remove(){rows.splice(rows.indexOf(this),1)},querySelector:s=>s==='.content-index-meta'?meta:null,meta})}};const root={querySelector(selector){const key=selector.match(/^\[data-index-count="(.+)"\]$/)?.[1];return key?counts[key]:selector==='#contentIndex'?holder:null}};let entries=[];const deps={getRoot:()=>root,getCalendarEntries:()=>entries,calendarContentVersions:entry=>entry.extendedProps?.contentVersions?.filter(item=>item?.url)||[],escapeHtml:value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),projectDate:value=>`DATE:${value||'none'}`,automationStageLabel:value=>`STAGE:${value||'none'}`};return {view:View.create(deps),counts,rows,holder,setEntries:value=>{entries=value},get empty(){return empty}}}
  assert.throws(()=>View.create(),/requires getRoot/);let h=harness();assert.equal(Object.isFrozen(h.view),true);assert.equal(h.view.isVisible(),true);h.holder.offsetParent=null;assert.equal(h.view.isVisible(),false);assert.throws(()=>View.create({getRoot:()=>({querySelector:()=>null}),getCalendarEntries:()=>[],calendarContentVersions(){},escapeHtml(){},projectDate(){},automationStageLabel(){}}).render([]),/missing #contentIndex/);
  h=harness();const projects=[{project_id:'A<&',name:'Alpha<&',current_stage:3,updated_at:'2026',automation_status:'failed',automation_stage:'video_complete_scene-02',automation_error_message:'bad<&',is_automated:true,automation_endpoint:'4',automation_voice_total:2,automation_voice_done:9,automation_images_total:3,automation_images_done:1,automation_videos_total:4,automation_videos_done:2},{project_id:'B',name:'Beta',automation_status:'running',automation_stage:'image_generate',is_automated:true,automation_endpoint:'5',automation_voice_total:1,automation_voice_done:1,automation_images_total:2,automation_images_done:9},{project_id:'C',name:'Legacy',automation_status:'cancelled',automation_stage:'video_complete'},{project_id:'D',name:'Versioned',automation_status:'succeeded'}];h.setEntries([{title:'Alpha',extendedProps:{projectId:'A<&',contentUrl:'/a.mp4',status:'scheduled'}},{title:'Legacy',extendedProps:{contentUrl:'/legacy.mp4',status:'scheduled'}},{title:'Versioned',extendedProps:{projectId:'D',contentVersions:[{url:'/v.mp4'}]}},{title:'Beta',extendedProps:{projectId:'B',status:'scheduled'}}]);h.view.render(projects);assert.deepEqual(Object.fromEntries(Object.entries(h.counts).map(([key,node])=>[key,node.textContent])),{all:'04',progress:'01',completed:'03',scheduled:'03'});assert.match(h.rows[0].html,/A&lt;&amp;/);assert.match(h.rows[0].html,/title="bad&lt;&amp;"/);assert.match(h.rows[0].meta.html,/음성 2\/2/);assert.match(h.rows[0].meta.html,/장면 이미지 1\/3/);assert.match(h.rows[0].meta.html,/Kling 영상 2\/4/);assert.match(h.rows[1].meta.html,/장면 이미지 2\/2/);
  h.view.render([]);assert.match(h.empty,/아직 제작한 콘텐츠가 없습니다/);assert.equal(h.rows.length,0);
  console.log('Step01 project index view tests passed');
})();
