const assert=require('node:assert/strict');
const SceneVideo=require('../01_app/assets/steps/step03/scene-video-controller.js');
(async()=>{
  const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}};
  function el(){const listeners={};return {dataset:{},disabled:false,textContent:'',value:'',addEventListener:(n,f)=>listeners[n]=f,removeEventListener:n=>delete listeners[n],emit:(n,event={})=>listeners[n]?.(event),listeners,querySelector(){return null},querySelectorAll(){return []},closest(){return null}}}
  function harness(options={}){let project=options.project===undefined?'p1':options.project;const images=new Map(),videos=new Map(),candidates=new Map(),message=el(),bulk=el(),grid=el(),cards=[];function card(id){const c=el(),status=el(),positive=el(),negative=el(),button=el(),label=el();c.dataset.scene=id;positive.value=`move-${id}`;negative.value=`no-${id}`;label.textContent=id.toUpperCase();button.closest=selector=>selector==='.storyboard-card'?c:null;c.querySelector=selector=>({'.storyboard-video-status':status,'.storyboard-motion-positive':positive,'.storyboard-motion-negative':negative,'.storyboard-video-generate':button,'.storyboard-card-head b':label}[selector]||null);c.parts={status,positive,negative,button,label};cards.push(c);return c}const root={querySelector:selector=>selector==='#storyboardGrid'?grid:selector==='#storyboardVideoBulkGenerate'?bulk:selector==='#storyboardMessage'?message:(selector.startsWith('.storyboard-card')?cards.find(c=>selector.includes(c.dataset.scene)):null),querySelectorAll:selector=>selector==='.storyboard-card'?cards:[]};const calls=[],errors=[];let request=options.request|| (async(url,init)=>{calls.push([url,init]);return {video_job:{status:'succeeded',video:{artifact_id:'v1',uri:'/v.mp4'}}}});const deps={getRoot:()=>root,request:(...args)=>request(...args),sleep:async ms=>calls.push(['sleep',ms]),getActiveProjectId:()=>project,getImages:()=>images,getVideos:()=>videos,getVideoCandidates:()=>candidates,renderStoryboardGrid:()=>calls.push(['render']),escapeSelector:value=>value,onError:(feature,error)=>errors.push([feature,error.message])};return {controller:SceneVideo.create(deps),root,grid,bulk,message,cards,card,images,videos,candidates,calls,errors,setProject:value=>project=value,setRequest:value=>request=value}}
  const valid={getRoot(){},request(){},sleep(){},getActiveProjectId(){},getImages(){},getVideos(){},getVideoCandidates(){},renderStoryboardGrid(){},escapeSelector(){},onError(){}};assert.throws(()=>SceneVideo.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>SceneVideo.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.mount(h.root),true);assert.equal(Object.keys(h.grid.listeners).length,1);assert.equal(h.controller.unmount(),true);assert.equal(Object.keys(h.grid.listeners).length,0);assert.equal(h.controller.mount(h.root),true);
  let c=h.card('s1');await assert.rejects(()=>h.controller.generate(c.parts.button),/이미지를 먼저/);assert.equal(h.calls.length,0);h.setProject(null);await assert.rejects(()=>h.controller.generate(c.parts.button),/프로젝트/);
  h=harness();c=h.card('s1');h.images.set('s1',{});const video=await h.controller.generate(c.parts.button,false);assert.equal(video.uri,'/v.mp4');assert.deepEqual(JSON.parse(h.calls[0][1].body),{project_id:'p1',scene_id:'s1',force:false,motion_prompt:'move-s1',negative_prompt:'no-s1'});assert.equal(h.videos.get('s1').uri,'/v.mp4');assert.equal(h.candidates.get('s1')[0].selected,true);assert.equal(c.parts.button.disabled,false);
  h=harness({request:async url=>{h.calls.push([url]);return h.calls.filter(x=>x[0]?.includes('video-status')).length===1?{status:'running'}:{status:'succeeded',video:{artifact_id:'vp',uri:'/poll.mp4'}}}});c=h.card('s2');const polled=await h.controller.poll(c,'task');assert.equal(polled.uri,'/poll.mp4');assert.deepEqual(h.calls.filter(x=>x[0]==='sleep').map(x=>x[1]),[1200,5000]);assert.equal(c.parts.status.textContent,'Kling 작업 대기 중…');
  h=harness({request:async()=>({status:'failed'})});c=h.card('s');await assert.rejects(()=>h.controller.poll(c,'t'),/실패/);
  h=harness({request:async()=>({status:'succeeded',video:{artifact_id:'missing-uri'}})});c=h.card('s');await assert.rejects(()=>h.controller.poll(c,'missing-uri'),/주소를 받지 못했습니다/);
  h=harness({request:async()=>({status:'queued'})});c=h.card('s');let sleeps=0;h.setRequest(async()=>({status:'queued'}));const oldSleep=h.calls;await assert.rejects(()=>h.controller.poll(c,'timeout'),/초과/);assert.equal(h.calls.filter(x=>x[0]==='sleep').length,180);
  const p1Jobs=deferred(),p2Jobs=deferred(),p1Again=deferred(),jobCounts={p1:0,p2:0};h=harness({request:async url=>{const id=new URL(url,'https://local').searchParams.get('project_id');jobCounts[id]+=1;if(id==='p1')return jobCounts.p1===1?p1Jobs.promise:p1Again.promise;return p2Jobs.promise}});h.controller.mount(h.root);const firstP1=h.controller.resume();h.setProject('p2');const firstP2=h.controller.resume();h.setProject('p1');await h.controller.resume();assert.deepEqual(jobCounts,{p1:1,p2:1});p1Jobs.resolve({jobs:[]});await firstP1;const secondP1=h.controller.resume();assert.equal(jobCounts.p1,2);p1Again.resolve({jobs:[]});await secondP1;h.setProject('p2');p2Jobs.resolve({jobs:[]});await firstP2;
  h=harness({request:async url=>url.includes('video-jobs')?{jobs:[{task_id:'broken',scene_id:'s'}]}:{status:'failed'}});c=h.card('s');h.controller.mount(h.root);await h.controller.resume();await new Promise(resolve=>setImmediate(resolve));assert.equal(c.parts.status.textContent,'Kling 영상 생성에 실패했습니다.');assert.equal(h.message.textContent,'Kling 영상 생성에 실패했습니다.');assert.deepEqual(h.errors,[['resume-poll','Kling 영상 생성에 실패했습니다.']]);
  h=harness();c=h.card('s');h.images.set('s',{});const late=deferred();h.setRequest(async()=>late.promise);const pending=h.controller.generate(c.parts.button);h.setProject('p2');late.resolve({video_job:{status:'succeeded',video:{artifact_id:'late',uri:'/late'}}});assert.equal(await pending,undefined);assert.equal(h.videos.size,0);
  h=harness();const active=0,max={value:0};let concurrent=0;h.setRequest(async(url,init)=>{if(url.includes('video-generate')){concurrent+=1;max.value=Math.max(max.value,concurrent);await Promise.resolve();concurrent-=1;const scene=JSON.parse(init.body).scene_id;return {video_job:{status:'succeeded',video:{artifact_id:scene,uri:`/${scene}.mp4`}}}}});['a','b','c'].forEach(id=>{h.card(id);h.images.set(id,{})});const results=await h.controller.generateMissing();assert.deepEqual(results.map(v=>v.artifact_id),['a','b','c']);assert.ok(max.value<=2);assert.equal(h.bulk.disabled,false);assert.equal(h.bulk.textContent,'미생성 Kling 영상 일괄 생성');
  h=harness();const gates=[deferred(),deferred()];let bulkRequests=0;h.setRequest(async()=>gates[bulkRequests++].promise);['a','b','c'].forEach(id=>{h.card(id);h.images.set(id,{})});const staleBulk=h.controller.generateMissing();await Promise.resolve();h.setProject('p2');gates.forEach((gate,index)=>gate.resolve({video_job:{status:'succeeded',video:{artifact_id:String(index),uri:`/${index}.mp4`}}}));await staleBulk;assert.equal(bulkRequests,2);assert.equal(h.videos.size,0);
  h=harness();c=h.card('s');await assert.rejects(()=>h.controller.generateMissing(),/S 이미지를 먼저/);
  h=harness();c=h.card('s');h.images.set('s',{});h.controller.mount(h.root);await h.grid.emit('click',{target:{closest:()=>c.parts.button}});assert.equal(h.videos.has('s'),true);h.videos.clear();await h.bulk.emit('click');assert.equal(h.videos.has('s'),true);
  console.log('Scene video controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
