const assert=require('node:assert/strict');const Voice=require('../01_app/assets/steps/step03/scene-voice-controller.js');const Playback=require('../01_app/assets/steps/step03/scene-voice-playback-controller.js');
(async()=>{
  const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
  function el(){const listeners={},classes=new Set(),attrs={};return {dataset:{},disabled:false,hidden:true,title:'',textContent:'',src:'',listeners,classes,attrs,addEventListener:(n,f)=>listeners[n]=f,removeEventListener:n=>delete listeners[n],emit:(n,e)=>listeners[n]?.(e),classList:{add:n=>classes.add(n),remove:n=>classes.delete(n),toggle:(n,v)=>v?classes.add(n):classes.delete(n),contains:n=>classes.has(n)},setAttribute:(n,v)=>attrs[n]=v,querySelector(){return null},querySelectorAll(){return []},closest(){return null},pause(){this.pauses=(this.pauses||0)+1},async play(){this.plays=(this.plays||0)+1}}}
  function harness(options={}){let project=options.project===undefined?'p1':options.project,profile=options.profile||'warm',clips=options.clips||new Map(),document=options.document||{production:{timeline:{scenes:[]}}};const grid=el(),bulk=el(),audio=el(),message=el(),cards=[],calls=[],errors=[];function card(id){const c=el(),button=el(),usage=el();c.dataset.scene=id;button.closest=s=>s==='.storyboard-card'?c:null;c.querySelector=s=>s==='.storyboard-speaker'?button:s==='.storyboard-voice-usage'?usage:null;c.parts={button,usage};cards.push(c);return c}const root={querySelector:s=>s==='#storyboardGrid'?grid:s==='#storyboardVoiceBulkGenerate'?bulk:s==='#storyboardVoiceAudio'?audio:s==='#storyboardMessage'?message:null,querySelectorAll:s=>s==='.storyboard-card'?cards:[]};let request=options.request|| (async(url,init)=>{calls.push(['request',url,init]);return {voice:{uri:'/voice.mp3',profile_id:profile,usage:{total_tokens:9,input_tokens:4,output_tokens:5}},timeline:{id:'timeline'}}});const playback=Playback.create({getRoot:()=>root});const deps={getRoot:()=>root,request:(...a)=>request(...a),getActiveProjectId:()=>project,getStoryboardDocument:()=>document,getVoiceClips:()=>clips,getSelectedVoiceProfile:()=>profile,setDemoTimeline:v=>calls.push(['setTimeline',v]),applyTimeline:v=>calls.push(['applyTimeline',v]),onError:(f,e)=>errors.push([f,e.message]),playback};return {controller:Voice.create(deps),playback,root,grid,bulk,audio,message,cards,card,calls,errors,get clips(){return clips},setProject:v=>project=v,setProfile:v=>profile=v,setClips:v=>clips=v,setDocument:v=>document=v,setRequest:v=>request=v}}
  const valid={getRoot(){},request(){},getActiveProjectId(){},getStoryboardDocument(){},getVoiceClips(){},getSelectedVoiceProfile(){},setDemoTimeline(){},applyTimeline(){},onError(){},playback:{updateControls(){},applyGenerated(){},play(){},pause(){}}};assert.throws(()=>Voice.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>Voice.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);h.controller.mount(h.root);h.controller.mount(h.root);assert.equal(Object.keys(h.grid.listeners).length,1);h.controller.unmount();assert.equal(Object.keys(h.grid.listeners).length,0);const missingDom=harness();assert.throws(()=>missingDom.controller.mount({querySelector:()=>null}),/missing #storyboardGrid/);await assert.rejects(()=>h.controller.generateOrPlay(null),/버튼/);h.setProject(null);const invalidButton=el();await assert.rejects(()=>h.controller.generateOrPlay(invalidButton),/프로젝트/);h.setProject('p1');await assert.rejects(()=>h.controller.generateOrPlay(invalidButton),/장면/);const noScene=el(),noSceneCard=el();noScene.closest=()=>noSceneCard;await assert.rejects(()=>h.controller.generateOrPlay(noScene),/장면 ID/);
  const doc={production:{timeline:{scenes:[{id:'s1',narration_cue_ids:['c1']},{id:'s2',narration_cue_ids:['c1']},{id:'s3',narration_cue_ids:[]}]}}};h=harness({document:doc});h.clips.set('s1',{uri:'/fallback',profile_id:'warm'});let ctx=h.controller.context('s2');assert.equal(ctx.ownerId,'s1');assert.equal(ctx.shared,true);assert.equal(ctx.ownerLabel,'S#01');assert.equal(ctx.voice.uri,'/fallback');h.clips.set('cue',{uri:'/cue',cue_id:'c1',profile_id:'warm'});assert.equal(h.controller.context('s2').voice.uri,'/cue');h.setProfile('other');assert.equal(h.controller.context('s2').voice,null);ctx=h.controller.context('s3');assert.equal(ctx.ownerId,'s3');assert.equal(ctx.shared,false);
  h=harness({document:doc});const owner=h.card('s1'),follower=h.card('s2'),plain=h.card('s3');h.clips.set('s1',{uri:'/saved',usage:{total_tokens:1000}});h.controller.updateControls();assert.equal(owner.parts.button.attrs['aria-label'],'저장된 음성 재생');assert.equal(owner.parts.button.classes.has('has-audio'),true);assert.equal(follower.parts.button.disabled,false);assert.match(follower.parts.usage.textContent,/S#01 음성 이어 사용/);assert.equal(plain.parts.button.title,'이 내레이션 음성 생성');assert.match(owner.parts.usage.textContent,/1,000/);
  h=harness({document:doc});const savedCard=h.card('s1');h.clips.set('s1',{uri:'/saved'});await h.controller.generateOrPlay(savedCard.parts.button,true);assert.equal(h.audio.src,'/saved');assert.equal(h.audio.pauses,1);assert.equal(h.audio.plays,1);const before=h.audio.plays;await h.controller.generateOrPlay(savedCard.parts.button,false);assert.equal(h.audio.plays,before);assert.equal(h.calls.length,0);const followerCard=h.card('s2');h.clips.clear();await h.controller.generateOrPlay(followerCard.parts.button);assert.match(h.message.textContent,/S#01에서 음성을 생성/);assert.equal(h.calls.length,0);
  h=harness({document:doc});const generatedCard=h.card('s1');const generated=await h.controller.generateOrPlay(generatedCard.parts.button);assert.equal(generated.uri,'/voice.mp3');assert.deepEqual(JSON.parse(h.calls[0][2].body),{project_id:'p1',scene_id:'s1'});assert.equal(h.clips.get('s1').uri,'/voice.mp3');assert.deepEqual(h.calls.slice(1,3).map(x=>x[0]),['setTimeline','applyTimeline']);assert.match(generatedCard.parts.usage.textContent,/음성 사용 토큰 9/);assert.equal(h.message.textContent,'내레이션 음성을 저장했습니다. 연결된 씬은 같은 음성을 이어 사용합니다.');assert.equal(h.audio.plays,1);assert.equal(generatedCard.parts.button.disabled,false);
  h=harness({document:doc,request:async()=>({voice:{}})});const missing=h.card('s1');await assert.rejects(()=>h.controller.generateOrPlay(missing.parts.button),/주소를 받지 못했습니다/);assert.equal(h.clips.size,0);assert.equal(missing.parts.button.disabled,false);
  h=harness({document:doc});const playFail=h.card('s1');h.audio.play=async()=>{throw new Error('play failed')};await assert.rejects(()=>h.controller.generateOrPlay(playFail.parts.button),/play failed/);assert.equal(h.clips.get('s1').uri,'/voice.mp3');assert.equal(playFail.parts.button.disabled,false);
  const gate=deferred();let paid=0;h=harness({document:doc,request:async()=>{paid+=1;return gate.promise}});const duplicate=h.card('s1');const d1=h.controller.generateOrPlay(duplicate.parts.button,false),d2=h.controller.generateOrPlay(duplicate.parts.button,false);assert.equal(paid,1);gate.resolve({voice:{uri:'/one'}});await Promise.all([d1,d2]);
  const staleGate=deferred(),mapA=new Map();h=harness({document:doc,clips:mapA,request:async()=>staleGate.promise});const staleCard=h.card('s1');const stale=h.controller.generateOrPlay(staleCard.parts.button);h.setProject('p2');staleGate.resolve({voice:{uri:'/late'},timeline:{late:true}});assert.equal(await stale,undefined);assert.equal(mapA.size,0);assert.equal(h.calls.length,0);assert.equal(h.audio.plays,undefined);assert.equal(h.message.textContent,'');
  const abaGate=deferred(),mapA2=new Map();h=harness({document:doc,clips:mapA2,request:async()=>abaGate.promise});const abaCard=h.card('s1'),aba=h.controller.generateOrPlay(abaCard.parts.button);h.setProject('p2');h.setClips(new Map());h.setProject('p1');abaGate.resolve({voice:{uri:'/late'}});assert.equal(await aba,undefined);assert.equal(mapA2.size,0);h=harness({document:doc,request:async()=>abaGate.promise});
  const profileGate=deferred();h=harness({document:doc,request:async()=>profileGate.promise});const profileCard=h.card('s1'),profileRun=h.controller.generateOrPlay(profileCard.parts.button);h.setProfile('other');profileGate.resolve({voice:{uri:'/late'}});assert.equal(await profileRun,undefined);assert.equal(h.clips.size,0);
  h=harness({document:doc});const b1=h.card('s1'),b2=h.card('s2'),b3=h.card('s3');await h.controller.generateMissing();assert.deepEqual(h.calls.filter(x=>x[0]==='request').map(x=>JSON.parse(x[2].body).scene_id),['s1','s3']);assert.equal(h.audio.pauses,1);assert.match(h.message.textContent,/미생성 내레이션 2개/);assert.equal(h.bulk.disabled,false);assert.equal(h.bulk.textContent,'미생성 음성 일괄 생성');
  const bulkGate=deferred();h=harness({document:doc,request:async()=>bulkGate.promise});h.card('s1');h.card('s2');h.card('s3');const bulkRun=h.controller.generateMissing();await Promise.resolve();h.setProject('p2');bulkGate.resolve({voice:{uri:'/late'}});await bulkRun;assert.equal(h.clips.size,0);assert.equal(h.calls.length,0);
  h=harness({document:doc,request:async()=>{throw new Error('voice fail')}});const clickCard=h.card('s1');h.controller.mount(h.root);await h.grid.emit('click',{target:{closest:s=>s==='.storyboard-speaker'?clickCard.parts.button:null}});assert.equal(h.message.textContent,'voice fail');assert.deepEqual(h.errors,[['generate','voice fail']]);await h.bulk.emit('click');assert.deepEqual(h.errors.at(-1),['bulk','voice fail']);assert.equal(h.bulk.disabled,false);
  console.log('Scene voice controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
