const assert=require('node:assert/strict');const Renderer=require('../01_app/assets/steps/step03/storyboard-grid-renderer.js');
(()=>{
  function harness(options={}){const order=[],images=options.images||new Map(),imageCandidates=options.imageCandidates||new Map(),videos=options.videos||new Map(),videoCandidates=options.videoCandidates||new Map(),grid={_html:'',set innerHTML(value){this._html=value;order.push('html')},get innerHTML(){return this._html}},root={querySelector:s=>s==='#storyboardGrid'?grid:null},storage={getItem:key=>{order.push(`storage:${key}`);return options.savedLook??null}},document=options.document||{production:{timeline:{scenes:[]}}},lines=options.lines||[];const deps={getRoot:()=>root,storage,getActiveProjectId:()=>options.projectId||'p1',getStoryboardLook:()=>options.look||'original',applyStoryboardLook:value=>order.push(`look:${value}`),getStoryboardDocument:()=>document,getCurrentScriptLines:()=>lines,getImages:()=>images,getImageCandidates:()=>imageCandidates,getVoiceContext:id=>(options.voices||{})[id]||{voice:null},getVideos:()=>videos,getVideoCandidates:()=>videoCandidates,escapeHtml:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),updateVoiceControls:()=>order.push('voice'),resumePendingVideos:()=>order.push('resume')};return {renderer:Renderer.create(deps),grid,order,images,imageCandidates,videos,videoCandidates}}
  const valid={getRoot(){},storage:{getItem(){}},getActiveProjectId(){},getStoryboardLook(){},applyStoryboardLook(){},getStoryboardDocument(){},getCurrentScriptLines(){},getImages(){},getImageCandidates(){},getVoiceContext(){},getVideos(){},getVideoCandidates(){},escapeHtml(){},updateVoiceControls(){},resumePendingVideos(){}};assert.throws(()=>Renderer.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>Renderer.create(copy),new RegExp(`requires ${name}`,'i'))}
  let h=harness({savedLook:'warm'});assert.equal(Object.isFrozen(h.renderer),true);assert.throws(()=>h.renderer.render(),/저장된 씬별 콘티/);assert.deepEqual(h.order,['storage:thinkcast-storyboard-look-p1','look:warm']);
  const scenes=[{id:'s<1',title:'제목 <A>',narration_cue_ids:['c1'],image_prompt:{text:'prompt <one>'},motion_prompt:{text:'move <one>'},narration:{text:'scene one'}},{id:'s2',title:'둘',narration_cue_ids:['c2'],image_prompt:{text:'prompt two'},narration:{text:'scene fallback'}},{id:'s3',title:'셋',narration_cue_ids:['missing'],narration:{text:'scene <three>'}}],document={production:{timeline:{scenes},narration_cues:[{id:'c1',narration:{text:'cue one'}},{id:'c2',narration:{text:'cue <two>'}}],global_prompts:{negative:{text:'negative <x>'}}}},images=new Map([['s<1',{uri:'/img?<x>',model:'model<x>',usage:{total_tokens:12,input_tokens:5,output_tokens:7}}]]),imageCandidates=new Map([['s<1',[{uri:'/old'},{uri:'/img?<x>'}]]]),videos=new Map([['s2',{artifact_id:'v2',uri:'/video?<x>'}]]),videoCandidates=new Map([['s2',[{artifact_id:'v1',uri:'/v1'},{artifact_id:'v2',uri:'/video?<x>'}]]]);h=harness({document,lines:['line <script>',''],images,imageCandidates,videos,videoCandidates,voices:{'s<1':{voice:{usage:{total_tokens:8,input_tokens:3,output_tokens:5}}}}});const html=h.renderer.render();assert.equal((html.match(/class="storyboard-card"/g)||[]).length,3);assert.match(html,/data-scene="s&lt;1"/);assert.match(html,/line &lt;script&gt;/);assert.match(html,/cue &lt;two&gt;/);assert.match(html,/scene &lt;three&gt;/);assert.match(html,/prompt &lt;one&gt;/);assert.match(html,/negative &lt;x&gt;/);assert.match(html,/후보 2\/2/);assert.match(html,/사용 토큰 12/);assert.match(html,/storyboard-candidate-nav prev/);assert.match(html,/storyboard-speaker has-audio/);assert.match(html,/음성 사용 토큰 8/);assert.match(html,/src="\/video\?&lt;x&gt;"/);assert.match(html,/영상 후보 2\/2/);assert.match(html,/storyboard-video-candidate-nav next/);assert.match(html,/Kling 영상 생성 완료/);assert.match(html,/이미지 생성/);assert.deepEqual(h.order,['storage:thinkcast-storyboard-look-p1','look:original','html','voice','resume']);
  h=harness({document:{production:{timeline:{scenes:[{id:'only'}]},narration_cues:[]}},lines:[]});assert.match(h.renderer.render(),/순간 이동, 공중 부양/);assert.match(h.grid.innerHTML,/storyboard-result" hidden/);assert.doesNotMatch(h.grid.innerHTML,/storyboard-video-preview/);
  console.log('Storyboard grid renderer tests passed');
})();
