const assert=require('node:assert/strict');
const Playback=require('../01_app/assets/steps/step03/scene-voice-playback-controller.js');

(async()=>{
  function el(){const classes=new Set(),attrs={};return {dataset:{},disabled:false,hidden:true,title:'',textContent:'',src:'',classes,attrs,classList:{add:n=>classes.add(n),toggle:(n,v)=>v?classes.add(n):classes.delete(n)},setAttribute:(n,v)=>attrs[n]=v,querySelector(){return null},pause(){this.events.push('pause')},async play(){this.events.push('play')}}}
  function harness(){const audio=el();audio.events=[];const cards=[];function card(id){const value=el(),button=el(),usage=el();value.dataset.scene=id;value.querySelector=s=>s==='.storyboard-speaker'?button:s==='.storyboard-voice-usage'?usage:null;value.parts={button,usage};cards.push(value);return value}const root={querySelector:s=>s==='#storyboardVoiceAudio'?audio:null,querySelectorAll:s=>s==='.storyboard-card'?cards:[]};return {root,audio,cards,card,controller:Playback.create({getRoot:()=>root})}}
  assert.throws(()=>Playback.create(),/requires getRoot/);assert.throws(()=>Playback.create({getRoot:1}),/requires getRoot/);
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.mount(h.root),true);h.controller.unmount();assert.deepEqual(h.audio.events,['pause']);assert.equal(h.controller.unmount(),true);assert.deepEqual(h.audio.events,['pause']);
  assert.throws(()=>Playback.create({getRoot:()=>({querySelector:()=>null})}).mount(),/requires a DOM root/);
  assert.throws(()=>Playback.create({getRoot:()=>({querySelector:()=>null,querySelectorAll:()=>[]})}).mount(),/missing #storyboardVoiceAudio/);
  h=harness();const owner=h.card('s1'),follower=h.card('s2'),missing=h.card('s3');const contexts={s1:{voice:{uri:'/one',usage:{total_tokens:1234}},shared:false,ownerLabel:'S#01'},s2:{voice:null,shared:true,ownerLabel:'S#01'},s3:{voice:null,shared:false,ownerLabel:'S#03'}};h.controller.updateControls(id=>contexts[id]);assert.equal(owner.parts.button.attrs['aria-label'],'저장된 음성 재생');assert.equal(owner.parts.button.classes.has('has-audio'),true);assert.equal(owner.parts.usage.textContent,'음성 사용 토큰 1,234');assert.equal(follower.parts.button.disabled,true);assert.equal(follower.parts.button.title,'S#01 음성 이어 사용 · 첫 씬에서 생성');assert.equal(follower.parts.usage.textContent,'S#01 음성 이어 사용 · 추가 생성 없음');assert.equal(missing.parts.button.title,'이 내레이션 음성 생성');assert.equal(missing.parts.usage.hidden,true);
  assert.throws(()=>h.controller.updateControls(),/context resolver/);const malformed=h.card('bad');assert.throws(()=>h.controller.updateControls(id=>id==='bad'?null:contexts[id]),/카드 컨트롤/);
  h=harness();const generated=h.card('s1');h.controller.applyGenerated(generated,{uri:'/made',usage:{total_tokens:1200,input_tokens:300,output_tokens:900}});assert.equal(generated.parts.button.title,'저장된 음성 재생');assert.equal(generated.parts.usage.textContent,'음성 사용 토큰 1,200 (입력 300 / 출력 900)');assert.throws(()=>h.controller.applyGenerated(null,{uri:'/x'}),/유효한 생성/);
  await h.controller.play({uri:'/saved'},{pauseFirst:true});assert.equal(h.audio.src,'/saved');assert.deepEqual(h.audio.events,['pause','play']);const count=h.audio.events.length;await h.controller.play({uri:'/quiet'},{autoplay:false});assert.equal(h.audio.events.length,count);assert.equal(h.audio.src,'/saved');await assert.rejects(()=>h.controller.play({}),/음성 주소/);
  h.audio.play=async()=>{h.audio.events.push('play');throw new Error('blocked')};await assert.rejects(()=>h.controller.play({uri:'/fail'}),/blocked/);assert.equal(h.audio.src,'/fail');
  h.controller.pause();assert.equal(h.audio.events.at(-1),'pause');
  console.log('Scene voice playback controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
