const assert=require('node:assert/strict');const ImageController=require('../01_app/assets/steps/step03/scene-image-controller.js');
(async()=>{
  const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
  function el(){const listeners={};return {dataset:{},disabled:false,hidden:true,textContent:'',innerHTML:'',value:'',listeners,addEventListener:(n,f)=>listeners[n]=f,removeEventListener:n=>delete listeners[n],emit:(n,e={})=>listeners[n]?.(e),querySelector(){return null},querySelectorAll(){return []},closest(){return null}}}
  function harness(options={}){let project=options.project===undefined?'p1':options.project;const images=new Map(),candidates=new Map(),videos=new Map(),grid=el(),bulk=el(),message=el(),model=el(),cards=[],calls=[],errors=[];model.value=options.model===undefined?'nano:banana':options.model;function card(id){const c=el(),button=el(),result=el(),label=el();c.dataset.scene=id;label.textContent=id.toUpperCase();button.closest=s=>s==='.storyboard-card'?c:null;c.querySelector=s=>({'.storyboard-generate':button,'.storyboard-result':result,'.storyboard-card-head b':label}[s]||null);c.parts={button,result,label};cards.push(c);return c}const root={querySelector:s=>s==='#storyboardGrid'?grid:s==='#storyboardBulkGenerate'?bulk:s==='#storyboardMessage'?message:s==='#storyboardModel'?model:null,querySelectorAll:s=>s==='.storyboard-card'?cards:[]};let request=options.request|| (async(url,init)=>{calls.push(['request',url,init]);return {image:{status:'succeeded',artifact_id:'a1',uri:'/image.png',model:'banana',usage:{total_tokens:12,input_tokens:5,output_tokens:7}}}});const deps={getRoot:()=>root,request:(...a)=>request(...a),sleep:async ms=>{calls.push(['sleep',ms]);if(options.sleep)return options.sleep(ms)},getActiveProjectId:()=>project,getImages:()=>images,getImageCandidates:()=>candidates,getVideos:()=>videos,escapeHtml:v=>String(v).replaceAll('<','&lt;'),onError:(f,e)=>errors.push([f,e.message])};return {controller:ImageController.create(deps),root,grid,bulk,message,model,cards,card,calls,errors,images,candidates,videos,setProject:v=>project=v,setRequest:v=>request=v}}
  const valid={getRoot(){},request(){},sleep(){},getActiveProjectId(){},getImages(){},getImageCandidates(){},getVideos(){},escapeHtml(){},onError(){}};assert.throws(()=>ImageController.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>ImageController.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);h.controller.mount(h.root);h.controller.mount(h.root);assert.equal(Object.keys(h.grid.listeners).length,1);h.controller.unmount();assert.equal(Object.keys(h.grid.listeners).length,0);h.controller.mount(h.root);let c=h.card('s1');h.setProject(null);await assert.rejects(()=>h.controller.generate(c.parts.button),/프로젝트/);h.setProject('p1');await assert.rejects(()=>h.controller.generate(null),/버튼/);await assert.rejects(()=>h.controller.generate({closest:()=>null}),/장면/);h.model.value='bad';await assert.rejects(()=>h.controller.generate(c.parts.button),/모델 설정/);
  h=harness();c=h.card('s1');h.videos.set('s1',{uri:'/old'});h.videos.set('s2',{uri:'/keep'});h.candidates.set('s1',[{artifact_id:'a1',uri:'/old.png',selected:false},{artifact_id:'a2',selected:true}]);const image=await h.controller.generate(c.parts.button,false);assert.equal(image.uri,'/image.png');assert.deepEqual(JSON.parse(h.calls[0][2].body),{project_id:'p1',scene_id:'s1',provider:'nano',model:'banana',force:false});assert.match(c.parts.result.innerHTML,/사용 토큰 12/);assert.equal(h.images.get('s1').uri,'/image.png');assert.equal(h.candidates.get('s1').length,2);assert.equal(h.candidates.get('s1')[0].selected,true);assert.equal(h.candidates.get('s1')[1].selected,false);assert.equal(h.videos.has('s1'),false);assert.equal(h.videos.has('s2'),true);assert.equal(h.message.textContent,'씬 이미지가 생성되어 이 콘텐츠에 저장되었습니다.');assert.equal(c.parts.button.textContent,'다시 생성');
  h=harness({request:async()=>{throw new Error('<failure>')}});c=h.card('s');await assert.rejects(()=>h.controller.generate(c.parts.button),/failure/);assert.match(c.parts.result.innerHTML,/&lt;failure>/);assert.equal(c.parts.button.disabled,false);assert.equal(c.parts.button.textContent,'이미지 생성');
  const gate=deferred();let paid=0;h=harness({request:async()=>{paid+=1;return gate.promise}});c=h.card('s');const one=h.controller.generate(c.parts.button),two=h.controller.generate(c.parts.button);assert.equal(paid,1);gate.resolve({image:{status:'succeeded',artifact_id:'x',uri:'/x'}});await Promise.all([one,two]);
  const stale=deferred();h=harness({request:async()=>stale.promise});c=h.card('s');const pending=h.controller.generate(c.parts.button);h.setProject('p2');stale.resolve({image:{status:'succeeded',artifact_id:'late',uri:'/late'}});assert.equal(await pending,undefined);assert.equal(h.images.size,0);assert.equal(h.message.textContent,'');
  h=harness();['a','b','c','d','e'].forEach(id=>h.card(id));h.images.set('a',{});let active=0,max=0;h.setRequest(async(url,init)=>{active+=1;max=Math.max(max,active);await Promise.resolve();active-=1;const id=JSON.parse(init.body).scene_id;return {image:{status:'succeeded',artifact_id:id,uri:`/${id}`}}});await h.controller.generateMissing();assert.ok(max<=4);assert.equal(h.images.size,5);assert.equal(h.bulk.disabled,false);assert.equal(h.bulk.textContent,'미생성 씬 일괄 생성');
  h=harness();c=h.card('retry');let attempts=0;h.setRequest(async()=>{attempts+=1;if(attempts<3){const e=new Error('temporary');e.transient=true;throw e}return {image:{status:'succeeded',artifact_id:'ok',uri:'/ok'}}});await h.controller.generateMissing();assert.equal(attempts,3);assert.deepEqual(h.calls.filter(x=>x[0]==='sleep').map(x=>x[1]),[1500,3000]);
  const transientGate=deferred();h=harness({request:async()=>transientGate.promise});h.card('stale-retry');let staleRequests=0;h.setRequest(async(...args)=>{staleRequests+=1;return transientGate.promise});const staleRetry=h.controller.generateMissing();await Promise.resolve();h.setProject('p2');const transientError=new Error('temporary');transientError.transient=true;transientGate.reject(transientError);await staleRetry;assert.equal(staleRequests,1);assert.equal(h.calls.filter(x=>x[0]==='sleep').length,0);assert.equal(h.images.size,0);assert.equal(h.message.textContent,'');
  const backoffGate=deferred();h=harness({sleep:()=>backoffGate.promise});h.card('backoff');let backoffRequests=0;h.setRequest(async()=>{backoffRequests+=1;const error=new Error('temporary');error.transient=true;throw error});const backoffRun=h.controller.generateMissing();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.calls.filter(x=>x[0]==='sleep').length,1);h.setProject('p2');backoffGate.resolve();await backoffRun;assert.equal(backoffRequests,1);assert.equal(h.images.size,0);
  h=harness();h.card('bad');h.card('good');let badCalls=0;h.setRequest(async(url,init)=>{const id=JSON.parse(init.body).scene_id;if(id==='bad'){badCalls+=1;throw new Error('permanent')}return {image:{status:'succeeded',artifact_id:id,uri:`/${id}`}}});await h.controller.generateMissing();assert.equal(badCalls,1);assert.equal(h.images.has('good'),true);assert.match(h.message.textContent,/실패 1장/);
  const gates=[deferred(),deferred(),deferred(),deferred()];h=harness();['a','b','c','d','e'].forEach(id=>h.card(id));let requests=0;h.setRequest(async()=>gates[requests++].promise);const bulkPending=h.controller.generateMissing();await Promise.resolve();h.setProject('p2');gates.forEach((g,i)=>g.resolve({image:{status:'succeeded',artifact_id:String(i),uri:`/${i}`}}));await bulkPending;assert.equal(requests,4);assert.equal(h.images.size,0);assert.equal(h.message.textContent,'');
  h=harness();c=h.card('click');h.controller.mount(h.root);await h.grid.emit('click',{target:{closest:()=>c.parts.button}});assert.equal(h.images.has('click'),true);h.images.clear();await h.bulk.emit('click');assert.equal(h.images.has('click'),true);
  console.log('Scene image controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
