const assert=require('node:assert/strict');const Controller=require('../01_app/assets/steps/step03/voice-profile-controller.js');
(async()=>{
  const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
  function el(profile){const listeners={},classes=new Set(),attrs={};return {dataset:profile?{voiceProfile:profile}:{},listeners,classes,attrs,textContent:'',src:'',addEventListener:(n,f)=>listeners[n]=f,removeEventListener:n=>delete listeners[n],emit:(n,e)=>listeners[n]?.(e),classList:{add:n=>classes.add(n),remove:n=>classes.delete(n)},setAttribute:(n,v)=>attrs[n]=v,closest(){return null},pause(){this.pauses=(this.pauses||0)+1},async play(){this.plays=(this.plays||0)+1}}}
  function harness(options={}){let project=options.project===undefined?'p1':options.project,selected='warm_female';const picker=el(),audio=el(),message=el(),buttons=['warm_female','bright_female','steady_male','qwen_narrator','qwen_etp'].map(el),calls=[],revoked=[],errors=[];const root={querySelector:s=>s==='.voice-picker'?picker:s==='#voiceSampleAudio'?audio:s==='#scriptMessage'?message:null,querySelectorAll:s=>s==='[data-voice-profile]'?buttons:[]};let request=options.request|| (async(url,init)=>{calls.push(['request',url,init]);return {voice_profile:'bright_female'}}),fetcher=options.fetch|| (async(url,init)=>{calls.push(['fetch',url,init]);return {ok:true,blob:async()=>({blob:true})}}),urlIndex=0;const deps={getRoot:()=>root,request:(...a)=>request(...a),fetch:(...a)=>fetcher(...a),createObjectURL:blob=>{calls.push(['create',blob]);return `blob:${++urlIndex}`},revokeObjectURL:url=>{revoked.push(url);calls.push(['revoke',url])},getActiveProjectId:()=>project,getSelectedProfile:()=>selected,setSelectedProfile:value=>{selected=value;calls.push(['selected',value])},onError:(f,e)=>errors.push([f,e.message])};return {controller:Controller.create(deps),root,picker,audio,message,buttons,calls,revoked,errors,get selected(){return selected},setProject:v=>project=v,setRequest:v=>request=v,setFetch:v=>fetcher=v}}
  const valid={getRoot(){},request(){},fetch(){},createObjectURL(){},revokeObjectURL(){},getActiveProjectId(){},getSelectedProfile(){},setSelectedProfile(){},onError(){}};assert.throws(()=>Controller.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>Controller.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);assert.deepEqual(h.controller.getProfiles(),['warm_female','bright_female','steady_male','qwen_narrator','qwen_etp']);assert.equal(h.controller.setProfile('invalid'),'warm_female');assert.equal(h.selected,'warm_female');assert.equal(h.buttons[0].attrs['aria-pressed'],'true');assert.equal(h.buttons[1].attrs['aria-pressed'],'false');h.controller.mount(h.root);h.controller.mount(h.root);assert.equal(Object.keys(h.picker.listeners).length,1);h.controller.unmount();assert.equal(Object.keys(h.picker.listeners).length,0);assert.throws(()=>h.controller.mount({querySelector:()=>null}),/missing .voice-picker/);
  h=harness();const button=h.buttons[1];const result=await h.controller.preview(button);assert.equal(result.voice_profile,'bright_female');assert.deepEqual(JSON.parse(h.calls[0][2].body),{project_id:'p1',profile_id:'bright_female'});assert.equal(h.calls[1][0],'selected');assert.deepEqual(h.calls[2],['fetch','/api/voice/sample?profile=bright_female&v=greeting-20260928',{credentials:'same-origin',cache:'no-store'}]);assert.equal(h.audio.pauses,1);assert.equal(h.audio.src,'blob:1');assert.equal(h.audio.plays,1);assert.match(h.message.textContent,/선택한 샘플을 재생/);assert.equal(button.classes.has('loading'),false);
  h=harness({fetch:async()=>({ok:false,json:async()=>({error:'sample denied'})})});await assert.rejects(()=>h.controller.preview(h.buttons[0]),/sample denied/);assert.equal(h.buttons[0].classes.has('loading'),false);h=harness({fetch:async()=>({ok:false,json:async()=>{throw new Error('bad json')}})});await assert.rejects(()=>h.controller.preview(h.buttons[0]),/샘플 음성을/);assert.deepEqual(h.errors,[['sample-json','bad json']]);
  h=harness();h.audio.play=async()=>{throw new Error('play failed')};await assert.rejects(()=>h.controller.preview(h.buttons[0]),/play failed/);assert.deepEqual(h.revoked,['blob:1']);assert.equal(h.buttons[0].classes.has('loading'),false);
  const gate=deferred();let selects=0,fetches=0;h=harness({request:async()=>{selects+=1;return gate.promise},fetch:async()=>{fetches+=1;return {ok:true,blob:async()=>({})}}});const d1=h.controller.preview(h.buttons[0]),d2=h.controller.preview(h.buttons[0]);assert.equal(selects,1);gate.resolve({voice_profile:'warm_female'});await Promise.all([d1,d2]);assert.equal(fetches,1);
  const stale=deferred();h=harness({request:async()=>stale.promise});const staleRun=h.controller.preview(h.buttons[0]);h.setProject('p2');stale.resolve({voice_profile:'warm_female'});assert.equal(await staleRun,undefined);assert.equal(h.calls.length,0);assert.equal(h.audio.plays,undefined);assert.equal(h.message.textContent,'샘플 음성을 준비하고 있습니다.');
  const gates=[deferred(),deferred(),deferred()];let index=0;h=harness({request:async()=>gates[index++].promise});const a1=h.controller.preview(h.buttons[0]),b=h.controller.preview(h.buttons[1]),a2=h.controller.preview(h.buttons[0]);assert.equal(index,3);gates[0].resolve({voice_profile:'warm_female'});gates[1].resolve({voice_profile:'bright_female'});gates[2].resolve({voice_profile:'warm_female'});await Promise.all([a1,b,a2]);assert.equal(h.selected,'warm_female');assert.equal(h.audio.plays,1);
  h=harness();await h.controller.preview(h.buttons[0]);assert.deepEqual(h.revoked,[]);h.audio.onended();assert.deepEqual(h.revoked,['blob:1']);h.audio.onerror();assert.deepEqual(h.revoked,['blob:1']);await h.controller.preview(h.buttons[1]);await h.controller.preview(h.buttons[2]);assert.deepEqual(h.revoked,['blob:1','blob:2']);h.controller.mount(h.root);h.controller.unmount();assert.deepEqual(h.revoked,['blob:1','blob:2','blob:3']);
  h=harness({request:async()=>{throw new Error('select fail')}});h.controller.mount(h.root);await h.picker.emit('click',{target:{closest:s=>s==='[data-voice-profile]'?h.buttons[0]:null}});assert.equal(h.message.textContent,'select fail');assert.deepEqual(h.errors,[['preview','select fail']]);
  console.log('Voice profile controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
