const assert=require('node:assert/strict');
const ProductionWorkflow=require('../01_app/assets/steps/step03/production-workflow-controller.js');

(async()=>{
  function node(){const classes=new Set();return {hidden:true,textContent:'',style:{},className:'',classList:{add:name=>classes.add(name),remove:name=>classes.delete(name),contains:name=>classes.has(name)},querySelector(){return null},querySelectorAll(){return []}}}
  function role(){const item=node(),state=node();item.querySelector=selector=>selector==='.ai-role-state'?state:null;item.state=state;return item}
  function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}}
  function harness(overrides={}){const ids=['aiWorkflowModal','aiProgressBar','aiFootStatus','aiWorkflowSummary','aiNow'];const nodes=Object.fromEntries(ids.map(id=>[id,node()]));const roles=Array.from({length:6},role);nodes.aiWorkflowModal.querySelectorAll=selector=>selector==='.ai-role'?roles:[];const bodyClasses=new Set();const root={body:{classList:{add:name=>bodyClasses.add(name),remove:name=>bodyClasses.delete(name)}},querySelector:selector=>nodes[selector.slice(1)]||null};const calls=[];const deps={getRoot:()=>root,configureWorkflowModal:(type,config)=>{calls.push(['configure',type,config]);return overrides.badModal?{}:nodes.aiWorkflowModal},generateMissingSceneVideos:async()=>{calls.push(['videos']);if(overrides.video)return overrides.video()},request:async(...args)=>{calls.push(['request',...args]);if(overrides.requestError)throw overrides.requestError;return {ready:true}},getActiveProjectId:()=>overrides.projectId===undefined?'project-3':overrides.projectId,sleep:async ms=>calls.push(['sleep',ms]),setupSceneProgressBadges:(role,label)=>calls.push(['badges',roles.indexOf(role),label]),runDemoSceneProgress:async(role,callback)=>{calls.push(['demo',roles.indexOf(role)]);callback(1,2);callback(2,2)},showStep:step=>calls.push(['show',step])};return {controller:ProductionWorkflow.create(deps),nodes,roles,root,bodyClasses,calls}}
  const valid={getRoot(){},configureWorkflowModal(){},generateMissingSceneVideos(){},request(){},getActiveProjectId(){},sleep(){},setupSceneProgressBadges(){},runDemoSceneProgress(){},showStep(){}};assert.throws(()=>ProductionWorkflow.create(),/requires getRoot/);for(const name of Object.keys(valid)){const copy={...valid};delete copy[name];assert.throws(()=>ProductionWorkflow.create(copy),new RegExp(`requires ${name}`))}
  let h=harness();assert.equal(Object.isFrozen(h.controller),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.mount(h.root),true);assert.equal(h.controller.unmount(),true);assert.equal(h.controller.unmount(),true);const broken=harness();delete broken.nodes.aiNow;assert.throws(()=>broken.controller.mount(broken.root),/missing #aiNow/);
  h=harness({projectId:null});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/이미지를 제작할 콘텐츠를 먼저 선택/);assert.equal(h.calls.length,0);
  h=harness();h.controller.mount(h.root);assert.equal(await h.controller.run(),undefined);assert.equal(h.calls[0][0],'videos');assert.equal(h.calls[1][0],'configure');assert.equal(h.calls[1][1],'production');assert.equal(h.calls[1][2].roles.length,6);assert.deepEqual(h.calls.find(call=>call[0]==='request').slice(1),['/api/production/prepare',{method:'POST',body:JSON.stringify({project_id:'project-3'})}]);assert.deepEqual(h.calls.find(call=>call[0]==='badges'),['badges',1,'장면별 이미지 생성 상태']);assert.deepEqual(h.calls.find(call=>call[0]==='demo'),['demo',1]);assert.equal(h.roles.every(item=>item.classList.contains('done')),true);assert.equal(h.nodes.aiProgressBar.style.width,'100%');assert.equal(h.nodes.aiWorkflowModal.classList.contains('complete'),true);assert.equal(h.nodes.aiNow.textContent,'장면 이미지 구성이 완료되었습니다.');assert.match(h.nodes.aiWorkflowSummary.textContent,/영상 생성 전 장면별 이미지를 검수/);assert.equal(h.nodes.aiWorkflowModal.hidden,true);assert.equal(h.bodyClasses.has('modal-open'),false);assert.equal(h.calls.at(-1)[0],'show');assert.equal(h.calls.at(-1)[1],4);assert.equal(h.calls.some(call=>call[0]==='sleep'&&call[1]===1000),true);
  h=harness({requestError:new Error('prepare failed')});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/prepare failed/);assert.equal(h.nodes.aiNow.textContent,'이미지 구성을 완료하지 못했습니다.');assert.equal(h.nodes.aiWorkflowSummary.textContent,'장면 이미지 제작 중 문제가 발생했습니다.');assert.equal(h.nodes.aiFootStatus.textContent,'prepare failed');assert.equal(h.calls.some(call=>call[0]==='sleep'&&call[1]===1500),true);assert.equal(h.nodes.aiWorkflowModal.hidden,true);assert.equal(h.bodyClasses.has('modal-open'),false);assert.equal(h.calls.some(call=>call[0]==='show'),false);
  const waiting=deferred();h=harness({video:()=>waiting.promise});h.controller.mount(h.root);const first=h.controller.run();const second=h.controller.run();assert.strictEqual(first,second);assert.equal(h.calls.filter(call=>call[0]==='videos').length,1);assert.equal(h.calls.filter(call=>call[0]==='request').length,0);assert.equal(h.controller.unmount(),false);waiting.resolve();await first;assert.equal(h.calls.filter(call=>call[0]==='request').length,1);assert.equal(h.controller.unmount(),true);
  h=harness({badModal:true});h.controller.mount(h.root);await assert.rejects(()=>h.controller.run(),/configured workflow modal/);assert.equal(h.bodyClasses.has('modal-open'),false);assert.equal(h.nodes.aiWorkflowModal.hidden,true);
  console.log('Production workflow controller tests passed');
})().catch(error=>{console.error(error);process.exitCode=1});
